export class employee {
  id:number;
  empName:string;
  schoolId:number;
  school:any;
  name:string;
  cityId:number;
  address:string;
  tel:number;
  mobile:number;
  fax:any;
  webPage:any;
  faceBook:any;
  description:any;
  poBox:any;
  imageFile:any;
  extension:any;
  imageId:any;
  lkpSections:any;
  schoolAdm:any;
  yearlyStudRegs:any;
  insertUser:any;
  insertDate:any;
  updateUser:any;
  updateDate:any;
  specId:number;
  spec:any;
  value:any;
  parentId:number;
  typeId:number;
  jobId:number;
  isActive:any;

  }