export class StudRegVw {
  id: number;
  parentId: number;
  firstName: string;
  studentId: number;
  schoolId: number;
  sectionId: number;
  entryDate: Date;
  birthDate: Date;
  yearId: number;
  classId: number;
  classPrice: number;
  className: string;
  classSeqId: number;
  nextClassId: number;
  nextClassPrice: number;
  nextClassName: string;
  classSeqName: string;
  descountType: number;
  descountValue: number;
  tourId: number;
  tourTypeId: number;
  tourName: string;
  tourTypeName: string;
  tourPrice: number;
  busId: number;
  approvedId: number;
  approvedDate: Date;
  studentBrotherSeq: number;
  brotherDescountType: number;
  busNote: string;
  note: string;
  totalPrice: number;
  newClassId: number;
  brotherDescountName: string;
  section:any;
  newClassSeq:any;
  newClass1:any;
  studStatusId:any;
}
